<?php

namespace App\Repository;

/**
 * IcAcreditacionQrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcAcreditacionQrRepository extends \Doctrine\ORM\EntityRepository
{
	
	/**
	 * Metodo para obtener el ultimo codigo Qr
	 *
	 *
	 */
	public function getCodigoQr($tipo_codigo = null)
	{
		$em = $this->getEntityManager();
	
		$query = $em->createQuery('
					SELECT qr
					FROM FrontendBundle:IcAcreditacionQr qr 
					where qr.estatus = :estatus
					and     qr.tipo 	 = :tipo
					ORDER BY qr.id ASC
					')->setParameter('estatus', false)->setParameter('tipo', $tipo_codigo)
					->setMaxResults(1);
	
		return $query->getOneOrNullResult();
	}
	
}
