<?php

namespace App\Repository;

use App\Entity\IcBeneficio;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * IcBeneficioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcBeneficioRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, IcBeneficio::class);
    }
    /**
	 * Metodo para obtener todos los registros de beneficio
	 * 
	 */
    public function getBeneficios()
    {
        $em = $this->getEntityManager();
		$query = $em->createQuery('
			SELECT it FROM BackendBundle:IcBeneficio it ORDER BY it.id');

        return $query->getResult();

    }
}
