<?php

namespace App\Repository;

use App\Entity\IcInformacion;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * IcInformacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcInformacionRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, IcInformacion::class);
    }
    /**
	 * Metodo para obtener todos los registros de informacion
     * ordenados por el tipo de informacion
	 * 
	 */
    public function getInformacion()
    {
        $em = $this->getEntityManager();
		$query = $em->createQuery('
			SELECT it FROM BackendBundle:IcInformacion it ORDER BY it.id');

        return $query->getResult();

    }
}
