<?php

namespace App\Repository;

/**
 * IcTipoInformacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcTipoInformacionRepository extends \Doctrine\ORM\EntityRepository
{
}
