<?php

namespace App\Repository;

/**
 * IcTipoAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcTipoAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
