#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

procesos_logout:
    path: /logout

#
# Definicion de Rutas Frontend
#
#



frontend_news:
    path:       /clubTijuana/{post}
    controller: App\Controller\Frontend\ComunicacionController:showPost

frontend_news_category:
    path:       /club-tijuana/noticias/{category}
    controller: App\Controller\Frontend\ComunicacionController:listPostByCategory

frontend_players_category:
    path:       /club-tijuana/jugadores/{category}
    controller: App\Controller\Frontend\DeportivoController:listPlayersByCategory