#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

procesos_logout:
    path: /logout

#
# Definicion de Rutas Frontend
#
#

frontend_home:
    path: /
    controller: App\Controller\Frontend\HomeController:index

frontend_news:
    path:       /noticias/xoloitzcuintles/{post}/{titulo}
    controller: App\Controller\Frontend\ComunicacionController:showPost

frontend_news_category:
    path:       /noticias/{category}
    controller: App\Controller\Frontend\ComunicacionController:listPostByCategory

frontend_players_category:
    path:       /primer-equipo/{category}
    controller: App\Controller\Frontend\DeportivoController:listPlayersByCategory

frontend_schedule:
    path:       /calendario/{calendario}
    controller: App\Controller\Frontend\DeportivoController:getSchedule

frontend_coach:
    path:       /cuerpo-tecnico
    controller: App\Controller\Frontend\DeportivoController:getCoach


frontend_player:
    path:       /jugador/{player}/{name}
    controller: App\Controller\Frontend\DeportivoController:getPlayer

frontend_palmares:
    path:       /club-palmares
    controller: App\Controller\Frontend\DeportivoController:palmares

frontend_historia:
    path:       /historia
    controller: App\Controller\Frontend\ComunicacionController:historia

frontend_estadio:
    path:       /estadio
    controller: App\Controller\Frontend\ComunicacionController:estadio

frontend_eventos:
    path:       /estadio-eventos
    controller: App\Controller\Frontend\ComunicacionController:eventos

frontend_reglamento:
    path:       /reglamento
    controller: App\Controller\Frontend\ComunicacionController:reglamento


frontend_directiva:
    path:       /directiva
    controller: App\Controller\Frontend\ComunicacionController:directiva

frontend_palcos:
    path:       /palcos
    controller: App\Controller\Frontend\ComunicacionController:palcos
#
# HWIOAuthBundle Routes
#
#
facebook_login:
    path: /login/check-facebook

twitter_login:
    path: /login/check-twitter

google_login:
    path: /login/check-google

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

#
#Definicion de Rutas para las Galerias
#
#

frontend_galerias:
    path:     /galerias
    controller: App\Controller\Frontend\MediaController:index 

frontend_galeria_detalle:
    path:     /galerias/{galeria}/{slug}
    controller: App\Controller\Frontend\MediaController:show 