#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

procesos_logout:
    path: /logout

#
# Definicion de Rutas Frontend
#
#

frontend_home:
    path: /
    controller: App\Controller\Frontend\HomeController:index

frontend_news:
    path:       /clubTijuana/{post}
    controller: App\Controller\Frontend\ComunicacionController:showPost

frontend_news_category:
    path:       /club-tijuana/noticias/{category}
    controller: App\Controller\Frontend\ComunicacionController:listPostByCategory

frontend_players_category:
    path:       /club-tijuana/jugadores/{category}
    controller: App\Controller\Frontend\DeportivoController:listPlayersByCategory

frontend_schedule:
    path:       /club-tijuana/calendario/{calendario}
    controller: App\Controller\Frontend\DeportivoController:getSchedule

frontend_coach:
    path:       /club-tijuana/cuerpo-tecnico
    controller: App\Controller\Frontend\DeportivoController:getCoach

frontend_player:
    path:       /club-tijuana/detalle-jugador/{player}
    controller: App\Controller\Frontend\DeportivoController:getPlayer

